pluginManagement {
    repositories {
        maven { url = 'https://maven.minecraftforge.net/' }
        gradlePluginPortal()
    }
}
rootProject.name = 'crafty-cards-forge'
def target = providers.gradleProperty('mcTarget').getOrElse('1.21.7')
if (target == '1.21.11') rootProject.buildFileName = 'build-modern.gradle'
